/**
 * Created by mingzhang on 3/31/18.
 */
'use strict';

const knowledge = {
  aminoAcids: {
    "H": "Basic",
    "R": "Basic",
    "K": "Basic",
    "F": "Nonpolar (Hydrophobic)",
    "A": "Nonpolar (Hydrophobic)",
    "L": "Nonpolar (Hydrophobic)",
    "M": "Nonpolar (Hydrophobic)",
    "I": "Nonpolar (Hydrophobic)",
    "W": "Nonpolar (Hydrophobic)",
    "P": "Nonpolar (Hydrophobic)",
    "V": "Nonpolar (Hydrophobic)",
    "C": "Polar, uncharged",
    "G": "Polar, uncharged",
    "Q": "Polar, uncharged",
    "N": "Polar, uncharged",
    "S": "Polar, uncharged",
    "Y": "Polar, uncharged",
    "T": "Polar, uncharged",
    "D": "Acidic",
    "E": "Acidic"
  },
  codons: {
    'TTC': 'F',
    'GTG': 'V',
    'GGT': 'G',
    'AGA': 'R',
    'CCG': 'P',
    'CCA': 'P',
    'TCC': 'S',
    'GAG': 'E',
    'AGG': 'R',
    'GAC': 'D',
    'TCG': 'S',
    'AAA': 'K',
    'CTA': 'L',
    'GTT': 'V',
    'GCC': 'A',
    'GCT': 'A',
    'TTT': 'F',
    'GAT': 'D',
    'TAT': 'Y',
    'GGG': 'G',
    'CTG': 'L',
    'GAA': 'E',
    'CAA': 'Q',
    'CCT': 'P',
    'GGC': 'G',
    'TCT': 'S',
    'ATG': 'M',
    'CGA': 'R',
    'ATA': 'I',
    'TTG': 'L',
    'CAT': 'H',
    'CAG': 'Q',
    'TGG': 'W',
    'GTA': 'V',
    'AAG': 'K',
    'TGT': 'C',
    'CCC': 'P',
    'AAT': 'N',
    'ACC': 'T',
    'CGG': 'R',
    'TAC': 'Y',
    'ACG': 'T',
    'ACA': 'T',
    'CAC': 'H',
    'ATT': 'I',
    'CGC': 'R',
    'AAC': 'N',
    'CGT': 'R',
    'TTA': 'L',
    'GCA': 'A',
    'AGC': 'S',
    'ACT': 'T',
    'TGC': 'C',
    'TCA': 'S',
    'AGT': 'S',
    'GCG': 'A',
    'GGA': 'G',
    'GTC': 'V',
    'ATC': 'I',
    'CTC': 'L',
    'CTT': 'L',
    'TAA': 'STOP',
    'TGA': 'STOP',
    'TAG': 'STOP'
  },
  proteinTags: [
    ["FLAG","DYKDDDDK"],
    ["FLAG","DYKDHDI"],
    ["FLAG","DYKDHDG"],
    ["VSVG Tag","YTDIEMNRLGK"],
    ["SV40 NLS","PKKKRKV"],
    ["SV40 NLS","PKKKRKVG"],
    ["T7 Tag", "MASMTGGQQMG"],
    ["NLS", "KKRKV"],
    ["HA","YPYDVPDYA"],
    ["6xHIS","HHHHHH"],
    ["Myc","EQKLISEEDL"],
    ["TEV","ENLYFQG"],
    ["TEV","ENPYFQG"],
    ["Myr","MGSNKSKPKDASQRR"],
    ["Myr","MGSSKSKPKDPSQRA"],
    ["V5","GKPIPNPLLGLDST"],
    ["S15","KETAAAKFERQHMDS"],
    ["Strep Tag","WSHPQFEK"]
  ]
};


if (typeof module !== 'undefined' && module.parent) {
  module.exports = knowledge;
} else {

} 